### ISSUE TITLE
File Not Found: /proc/net/dev

### ISSUE THREAD

**Issue by alonb235** [hash3liZer/wifijammer#7]
I am getting an error when I try to run, line 398 getNICnames
`dev = open('/proc/net/dev', 'r')`

I get a file not found error: no such file or directory: '/proc/net/dev'

**Comment by hash3liZer** [comment]
Which OS you are running it on?

**Comment by hash3liZer** [comment]
Closing as of no response

**Comment by jginsburgn** [comment]
I am having the same trouble in macOS.
